#pragma once

struct Keyboard
{
    static bool a;
    static bool b;
    static bool c;
    static bool d;
    static bool e;
    static bool f;
    static bool g;
    static bool h;
    static bool i;
    static bool j;
    static bool k;
    static bool l;
    static bool m;
    static bool n;
    static bool o;
    static bool p;
    static bool q;
    static bool r;
    static bool s;
    static bool t;
    static bool u;
    static bool v;
    static bool w;
    static bool x;
    static bool y;
    static bool z;

    static bool zero;
    static bool one;
    static bool two;
    static bool three;
    static bool four;
    static bool five;
    static bool six;
    static bool seven;
    static bool eight;
    static bool nine;

    static bool f1;
    static bool f2;
    static bool f3;
    static bool f4;
    static bool f5;
    static bool f6;
    static bool f7;
    static bool f8;
    static bool f9;
    static bool f10;
    static bool f12;
    static bool f13;
    static bool f14;
    static bool f15;
    static bool f16;
    static bool f17;
    static bool f18;
    static bool f19;
    static bool f20;
    static bool f21;
    static bool f22;
    static bool f23;
    static bool f24;
    static bool f25;

    static bool leftShift;
    static bool rightShift;
    static bool leftCtrl;
    static bool rightCtrl;
    static bool leftAlt;
    static bool rightAlt;
    static bool leftSuper;
    static bool rightSuper;
    static bool capslock;
    static bool tab;
    static bool backSpace;
    static bool space;

    static bool upArrow;
    static bool downArrow;
    static bool leftArrow;
    static bool rightArrow;

    static bool del;
    static bool insert;
    static bool home;
    static bool end;
    static bool pageUp;
    static bool pageDown;

    static bool quotes;
    static bool semiColon;
    static bool comma;
    static bool dot;
    static bool forwardSlash;
    static bool backSlash;
    static bool leftSquareBracket;
    static bool rightSquareBracket;
    void reset();
};

inline bool Keyboard::a = false;
inline bool Keyboard::b = false;
inline bool Keyboard::c = false;
inline bool Keyboard::d = false;
inline bool Keyboard::e = false;
inline bool Keyboard::f = false;
inline bool Keyboard::g = false;
inline bool Keyboard::h = false;
inline bool Keyboard::i = false;
inline bool Keyboard::j = false;
inline bool Keyboard::k = false;
inline bool Keyboard::l = false;
inline bool Keyboard::m = false;
inline bool Keyboard::n = false;
inline bool Keyboard::o = false;
inline bool Keyboard::p = false;
inline bool Keyboard::q = false;
inline bool Keyboard::r = false;
inline bool Keyboard::s = false;
inline bool Keyboard::t = false;
inline bool Keyboard::u = false;
inline bool Keyboard::v = false;
inline bool Keyboard::w = false;
inline bool Keyboard::x = false;
inline bool Keyboard::y = false;
inline bool Keyboard::z = false;

inline bool Keyboard::zero = false;
inline bool Keyboard::one = false;
inline bool Keyboard::two = false;
inline bool Keyboard::three = false;
inline bool Keyboard::four = false;
inline bool Keyboard::five = false;
inline bool Keyboard::six = false;
inline bool Keyboard::seven = false;
inline bool Keyboard::eight = false;
inline bool Keyboard::nine = false;

inline bool Keyboard::f1 = false;
inline bool Keyboard::f2 = false;
inline bool Keyboard::f3 = false;
inline bool Keyboard::f4 = false;
inline bool Keyboard::f5 = false;
inline bool Keyboard::f6 = false;
inline bool Keyboard::f7 = false;
inline bool Keyboard::f8 = false;
inline bool Keyboard::f9 = false;
inline bool Keyboard::f10 = false;
inline bool Keyboard::f12 = false;
inline bool Keyboard::f13 = false;
inline bool Keyboard::f14 = false;
inline bool Keyboard::f15 = false;
inline bool Keyboard::f16 = false;
inline bool Keyboard::f17 = false;
inline bool Keyboard::f18 = false;
inline bool Keyboard::f19 = false;
inline bool Keyboard::f20 = false;
inline bool Keyboard::f21 = false;
inline bool Keyboard::f22 = false;
inline bool Keyboard::f23 = false;
inline bool Keyboard::f24 = false;
inline bool Keyboard::f25 = false;

inline bool Keyboard::leftShift = false;
inline bool Keyboard::rightShift = false;
inline bool Keyboard::leftCtrl = false;
inline bool Keyboard::rightCtrl = false;
inline bool Keyboard::leftAlt = false;
inline bool Keyboard::rightAlt = false;
inline bool Keyboard::leftSuper = false;
inline bool Keyboard::rightSuper = false;
inline bool Keyboard::capslock = false;
inline bool Keyboard::tab = false;
inline bool Keyboard::backSpace = false;
inline bool Keyboard::space = false;

inline bool Keyboard::upArrow = false;
inline bool Keyboard::downArrow = false;
inline bool Keyboard::leftArrow = false;
inline bool Keyboard::rightArrow = false;

inline bool Keyboard::del = false;
inline bool Keyboard::insert = false;
inline bool Keyboard::home = false;
inline bool Keyboard::end = false;
inline bool Keyboard::pageUp = false;
inline bool Keyboard::pageDown = false;

inline bool Keyboard::quotes = false;
inline bool Keyboard::semiColon = false;
inline bool Keyboard::comma = false;
inline bool Keyboard::dot = false;
inline bool Keyboard::forwardSlash = false;
inline bool Keyboard::backSlash = false;
inline bool Keyboard::leftSquareBracket = false;
inline bool Keyboard::rightSquareBracket = false;
